name: Build and deploy the Angular App to GitHub

on:
  push:
    branches: [main]

jobs:
  deploy-to-github:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v1
      with:
        node-version: 16.17.0

    - name: Install NPM dependencies
      run: npm install

    - name: Build Angular App
      run: npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/brennholzhaerter
